const APP_GREEN = "#14a028";
//const APP_BBUTTON_GREEN = "#009432";Blue - #0087dc
// Grey - #5f5f5f
// Green - #14a028
// Orange - #f08200
const APP_BUTTON_GREEN = "#14a028";
const APP_GREY = "#5f5f5f";
const APP_WHITE = "#fff";
const APP_ACTIVE_GREEN = "#48b833";
const APP_ACTIVE_RED = "red";
const APP_ACTIVE_ORANGE = "#f08200";

const DASHBOARD_IRR_GRAPH = '#fc9c3d';
const DASHBOARD_PWR_GRAPH = '#f01f1f';
const DASHBOARD_MNTHYIELD_GRAPH = '#b97f22';
export {
    APP_ACTIVE_ORANGE,APP_GREY,APP_BUTTON_GREEN,APP_GREEN,APP_WHITE,APP_ACTIVE_GREEN,APP_ACTIVE_RED,DASHBOARD_IRR_GRAPH,DASHBOARD_PWR_GRAPH,DASHBOARD_MNTHYIELD_GRAPH
}